chrome.webNavigation.onCompleted.addListener(
    function(currtab) {
        if (confirm("Press OK to automate 2FA process.")) {
            let password = prompt("What is your password?");
            console.log(currtab);
            chrome.tabs.sendMessage(
                currtab.tabId, {
                    reddit_automate: true,
                    reddit_password: password,
                }
            );
        }
    }, {
        url: [{
            urlMatches: 'https://www.reddit.com/settings/privacy'
        }]
    }
);

chrome.runtime.onMessage.addListener(
    function(request, sender, sendResponse) {
        if (request.scan_and_get_code) {
            let code = prompt("Download the Google Authenticator app, scan the provided QR code, and type the code generated by the app here");
            chrome.tabs.sendMessage(
                sender.tab.id, {
                    reddit_place_code: true,
                    reddit_code: code
                }
            );
        }
        if (request.reddit_finished) {
            confirm("Finished setting up 2FA");
        }
        if (request.auto_detect_setting) {
            sendResponse({ success: true });
            chrome.storage.sync.set({ auto_detect_setting: request.set_to }, function() {
                console.log('Auto detect setting is set to ' + request.set_to);
                sendResponse({ success: true });
            });
        }
        if (request.remember_accounts_setting) {
            chrome.storage.sync.set({ remember_accounts_setting: request.set_to }, function() {
                console.log('Remember accounts setting is set to ' + request.set_to);
                sendResponse({ success: true });
            });
        }
        if (request.get_settings) {
            console.log("Getting settings");
            let auto_detect_setting = false;
            let remember_accounts_setting = false;
            await chrome.storage.sync.get(['auto_detect_setting', 'remember_accounts_setting'], (result) => {
                auto_detect_setting = result.auto_detect_setting;
                remember_accounts_setting = result.remember_accounts_setting;
            });
            sendResponse({
                auto_detect_setting: auto_detect_setting != null ? auto_detect_setting : false,
                remember_accounts_setting: remember_accounts_setting != null ? remember_accounts_setting : false
            });
        }
    }
);